version: 0.2

phases:
  pre_build:
    commands:
      - echo Installing dependencies ...
      - npm ci
  build:
    commands:
      - echo Build Started on `date`
      - npm run build
  post_build:
    commands:
      - echo "BUCKET: $BUCKET_NAME"
      # - aws s3 cp --recursive ./dist s3://$BUCKET_NAME/
      # - aws s3 cp --cache-control="max-age=0, no-cache, no-store, must-revalidate" ./out/index.html s3://$BUCKET_NAME/
artifacts:
  files:
    - appspec.yml
    - "**/*"
  base-directory: "out"
