version: 0.2

phases:
  pre_build:
    commands:
      - echo Installing dependencies ...
      - npm ci
  build:
    commands:
      - echo Build Started on `date`
      - npm run build
  post_build:
    commands:
      - echo Uploading artifacts to S3...
      - aws s3 cp --recursive ./out s3://$BUCKET_NAME/
artifacts:
  files:
    - appspec.yml
    - "**/*"
  base-directory: "out"
